# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "674cffdc205f1a4bce610c83ec323182"
application_url = "https://paso-timber-identity-fountain.trycloudflare.com"
embedded = true
name = "monet loyalty studio"
handle = "monet-loyalty-studio"

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://paso-timber-identity-fountain.trycloudflare.com/auth/callback",
  "https://paso-timber-identity-fountain.trycloudflare.com/auth/shopify/callback",
  "https://paso-timber-identity-fountain.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "loyaltystudio.myshopify.com"
automatically_update_urls_on_dev = true
